### ISSUE TITLE
[Configuration] [Low] Problem on configuring winkey

### ISSUE THREAD

**Issue by spedruzzo** [NilsFC/Model-X#2]
Use case: I want to define a win key as tap instead long tab
expected : is working properly
issue : if I press only the key is working win key is pressed but if I press win key and "e" (launch explorer ) it write "<e" (< is the key conffigured as long tap)
Workaround : define the win key or other key for combination as long tap

![image](https://github.com/user-attachments/assets/9d85a5f4-c14c-49e6-88e9-0bb598aa98d9)

**Comment by NilsFC** [comment]
If I understood well you want:
-'Left GUI' when you press shortly (TAP)
-'Non-Us Backslash' when you keep pressed (HOLD)
In the way the firmware is compiled now, when you add a 2nd key, the 1st is interpreted as 'Holded'. This is called in ZMK 'hold-preferred' flavor.
It's very well described here: https://zmk.dev/docs/keymaps/behaviors/hold-tap

I suggest two possible solutions:
a) Invert TAP and HOLD keys, so that you have 'Non-Us Backlash' when you press shortly (<200ms) and 'Left GUI' when you HOLD the key (> 200ms). In this way if you keep the key pressed you can add a 2nd key and the 1st will be interpreted as HOLD and therefore as GUI (Windows).
b) Recompile the firmware with a different 'flavor' setting, maybe 'balanced' instead of 'hold-preferred';
